const PLAYERS_DATA = [
    { id: 1,  name: "Alan",       team: "Mexico" },
    { id: 2,  name: "Emily",      team: "South Africa" },
    { id: 3,  name: "Jackie",     team: "South Korea" },
    { id: 4,  name: "Amanda",     team: "Czech Republic" },
    { id: 5,  name: "Charlotte",  team: "Canada" },
    { id: 6,  name: "Maddy",      team: "Bosnia and Herzegovina" },
    { id: 7,  name: "Richard",    team: "Qatar" },
    { id: 8,  name: "Simon",      team: "Switzerland" },
    { id: 9,  name: "Katie",      team: "Brazil" },
    { id: 10, name: "Laura H",    team: "Morocco" },
    { id: 11, name: "Rosie",      team: "Haiti" },
    { id: 12, name: "Jackie",     team: "Scotland" },
    { id: 13, name: "Steve",      team: "USA" },
    { id: 14, name: "Hannah G",   team: "Paraguay" },
    { id: 15, name: "Richard",    team: "Australia" },
    { id: 16, name: "Jen",        team: "Turkey" },
    { id: 17, name: "Simon",      team: "Germany" },
    { id: 18, name: "Tom",        team: "Curaçao" },
    { id: 19, name: "Beccy",      team: "Ivory Coast" },
    { id: 20, name: "Ellen G",    team: "Ecuador" },
    { id: 21, name: "Iveta",      team: "Netherlands" },
    { id: 22, name: "Dennis",     team: "Japan" },
    { id: 23, name: "Richard",    team: "Sweden" },
    { id: 24, name: "Maddie",     team: "Tunisia" },
    { id: 25, name: "Richard",    team: "Belgium" },
    { id: 26, name: "Cam",        team: "Egypt" },
    { id: 27, name: "Amy",        team: "Iran" },
    { id: 28, name: "Claire S",   team: "New Zealand" },
    { id: 29, name: "Peter",      team: "Spain" },
    { id: 30, name: "Sarah H",    team: "Cape Verde" },
    { id: 31, name: "Sam",        team: "Saudi Arabia" },
    { id: 32, name: "Betsy",      team: "Uruguay" },
    { id: 33, name: "Edwina",     team: "France" },
    { id: 34, name: "Ellen B",    team: "Senegal" },
    { id: 35, name: "Dennis",     team: "Iraq" },
    { id: 36, name: "Clare",      team: "Norway" },
    { id: 37, name: "Alan",       team: "Argentina" },
    { id: 38, name: "Richard",    team: "Algeria" },
    { id: 39, name: "Jen",        team: "Austria" },
    { id: 40, name: "Sam",        team: "Jordan" },
    { id: 41, name: "Gavin",      team: "Portugal" },
    { id: 42, name: "Maddy",      team: "DR Congo" },
    { id: 43, name: "Emma Hall",  team: "Uzbekistan" },
    { id: 44, name: "Laura S",    team: "Colombia" },
    { id: 45, name: "Ellen B",    team: "England" },
    { id: 46, name: "Laura H",    team: "Croatia" },
    { id: 47, name: "Ellen G",    team: "Ghana" },
    { id: 48, name: "Steve",      team: "Panama" }
];
